### PR TITLE
Replace `simple-node-logger` with `pino` for Node 24 compatibility

### LINKED ISSUE #61: `simple-node-logger` crashes on Node.js v24 due to deprecated `util.isDate`
## Summary
Trying to compile an app with the newer versions of node crashes due to the dependency `simple-node-logger` which seems to be not maintained regularly as it uses a function (`util.isDate`) which is deprecated in the newer versions of node.

## Current Behaviour:

When trying to compile an app with node version 24, the below error is shown.

Image

## Expected Behaviour:
 
The logger should work without crashing

## Reproduction
```js
const logger = require('simple-node-logger').createSimpleLogger({
  timestampFormat: 'YYYY-MM-DD HH:mm:ss.SSS',
});
logger.setLevel('debug');
logger.info('hello');

### PR DESCRIPTION
**Pull request by Pratheek555**
## Summary
This PR replaces `simple-node-logger` usage with a native in-repo logger implementation in [`src/misc/logger.ts`](/home/pratheek/Desktop/gsoc/rocket.chat/Rocket.Chat.Apps-compiler/src/misc/logger.ts).

## Fixes
#61 

## Why
`simple-node-logger` is causing runtime compatibility issues on modern Node versions (notably Node 24), including crashes from deprecated/removed Node `util` APIs.  
Switching to a small native logger removes that runtime risk and avoids external logger dependency behavior.

## What changed
- Implemented `NativeLogger` with:
  - `setLevel()` support
  - level filtering (`trace`, `debug`, `info`, `warn`, `error`, `fatal`)
  - `debug`, `info`, `warn`, `error` methods
- Added timestamped log output format:
  - `[YYYY-MM-DD HH:mm:ss.SSS] LEVEL ...args`
- Preserved existing default behavior:
  - log level is initialized from `process.env.LOG_LEVEL` (defaulting to `info`)

---
The below logs were obtained while trying to compile a rocketchat app.
---

## Before logs: (ran by switching node version to 20)

image

## After Logs : (the new native logger)

image

## Validation
- `npx eslint src/**/*.ts` passes
- Logger API surface used by compiler code (`debug`, `info`, `warn`, `error`, `setLevel`) remains available

### CODE REVIEW

**Review by KevLehman — CHANGES_REQUESTED** [review]
Just use pino or a log library, no need to reinvent the wheel

**Comment by Pratheek555** [comment]
> Just use pino or a log library, no need to reinvent the wheel

yes sir, I already have it implemented in another branch. Will push the code in sometime.

thank you!

**Comment by Pratheek555** [comment]
Hey @KevLehman 

I have implemented pino with pino-pretty. The below shows the demonstration of the logs while compiling an app. Please do let me know if any changes are required.

image

Thank you for your time!

File: src/misc/logger.ts [hunk 1]
```diff
@@ -1,8 +1,14 @@
...
 
-logger.setLevel(process.env.LOG_LEVEL || "info");
+const logger = pino({
+    level: process.env.LOG_LEVEL || "info",
+    timestamp: pino.stdTimeFunctions.isoTime,
+    transport: {
+        target: "pino-pretty",
+        options: {
+            colorize: true,
+        },
```
Comment (Dnouv) [inline src/misc/logger.ts:10]: Thanks for the PR!
Per the Pino docs, the pretty print is more for the development phase; for production, they recommend the default NDJSON format.
Source: https://getpino.io/#/docs/pretty

Comment (Pratheek555) [reply src/misc/logger.ts:10]: Hey!
Apologize for the oversight, I was focused way too much on making the logs look like how it was previously. I have another branch where I have implemented only with pino. 

image

This is how the logs would look in the NDJSON format, is that fine?

Comment (Dnouv) [reply src/misc/logger.ts:10]: That definitely does not look user-friendly. Let's leave it with a pretty format if no other workaround.

Comment (Pratheek555) [reply src/misc/logger.ts:10]: I tried checking if i could make it as interpretable as possible, the max I could was change the levels to show the log level instead of a number.

image

I tried understanding why they don't recommend using pino-pretty for prod, the reason was it has to pipe each normal pino log through the pino-pretty which would cause some level of overhead. 
If I am not wrong, we don't have that many logs constantly being sent, we only log things when we compile, so I feel this should be good enough.  (sorry If I missed anything :( )

File: package.json [hunk 2]
```diff
@@ -59,6 +59,8 @@
         "fs-extra": "^8.1.0",
         "glob": "^7.1.4",
         "lodash.clonedeep": "^4.5.0",
+        "pino": "^10.3.1",
+        "pino-pretty": "^13.1.3",
         "simple-node-logger": "^18.12.24",
```
Comment (Dnouv) [inline package.json]: If this is no longer used, why not remove it?

Comment (Pratheek555) [reply package.json]: Right, I have edited the package.json and package-lock.json and pushed a commit.

**Review by d-gubert — APPROVED** [review]
